p2/base/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('login/', views.loginPage, name='login'),
    path('logout/', views.logoutUser, name='logout'),
    path('register/', views.registerPage, name='register'),
    path('', views.bienvenida, name="bienvenida"),
    path('listacursos/', views.listacursos, name="listacursos"),
    path('actualizar-curso/<str:pk>/', views.actualizarCurso, name="actualizar-curso"),
    path('eliminar-curso/<str:pk>/', views.eliminarCurso, name="eliminar-curso"),
    path('curso/<str:pk>/', views.curso, name="curso"),
    path('crear-estudiante/<str:pk>/', views.crearEstudiante, name="crear-estudiante"),
    path('actualizar-estudiante/<str:pk>/', views.actualizarEstudiante, name="actualizar-estudiante"),
    path('eliminar-estudiante/<str:pk>/', views.eliminarEstudiante, name="eliminar-estudiante"),
    path('listapruebas/', views.listapruebas, name="listapruebas"),
    path('actualizar-prueba/<str:pk>/', views.actualizarPrueba, name="actualizar-prueba"),
    path('eliminar-prueba/<str:pk>/', views.eliminarPrueba, name="eliminar-prueba"),
    path('prueba/<str:pk>/', views.prueba, name="prueba"),
    path('crear-preguntas/<str:pk>/', views.crearPreguntas, name="crear-preguntas"),
    path('actualizar-preguntas/<str:pk>/', views.actualizarPreguntas, name="actualizar-preguntas"),
    path('eliminar-preguntas/<str:pk>/', views.eliminarPreguntas, name="eliminar-preguntas"),
    path('pregunta/<str:pk>/', views.pregunta, name="pregunta"),
    path('relacionar-preguntas/<str:pk>/', views.relacionarPreguntas, name="relacionar-preguntas"),
    path('eliminar-relacion-preguntas/<str:pk>/', views.eliminarRelacionPreguntas, name="eliminar-relacion-preguntas"),
    path('listatemas/', views.listatemas, name="listatemas"),
    path('actualizar-tema/<str:pk>/', views.actualizarTema, name="actualizar-tema"),
    path('eliminar-tema/<str:pk>/', views.eliminarTema, name="eliminar-tema"),
]

p2/p2/urls.py
from django.contrib import admin
from django.urls import path, include 
import debug_toolbar

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('base.urls')),
    path('__debug__', include(debug_toolbar.urls)),
]

p2/base/models.py
from email.policy import default
from django.db import models
from django.contrib.auth.models import User

class Prueba(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='pruebas')
    nombre_prueba = models.CharField('Nombre Prueba', max_length=100)
    aciertoprueba = models.DecimalField(max_digits=4, decimal_places=3, blank=True, null=True)
    calificacionprueba = models.DecimalField(max_digits=3, decimal_places=2, blank=True, null=True)
    pruebareal = models.IntegerField('Numero de prueba', default=0)

    def __str__(self):
        return str(self.id) + '-' + self.nombre_prueba

class Tema(models.Model):
    nombre_tema = models.CharField('Nombre Tema', max_length=100)

    aciertotema = models.DecimalField(max_digits=4, decimal_places=3, blank=True, null=True)

    def __str__(self):
        return str(self.id) + '-' + self.nombre_tema

class Preguntas(models.Model):
    prueba = models.ForeignKey(Prueba, on_delete=models.CASCADE)
    tema = models.ForeignKey(Tema, on_delete=models.CASCADE)

    pregunta = models.CharField('Pregunta', max_length=100)
    acierto = models.DecimalField(max_digits=4, decimal_places=3, blank=True, null=True)
 
    def nombreprueba(self):
        return self.prueba.nombre_prueba

    def nombretema(self):
        return self.tema.nombre_tema

    def __str__(self):
        return str(self.id) + '-' + self.pregunta

class Curso(models.Model):
    nombre_curso = models.CharField('Nombre del Curso', max_length=100)

    def __str__(self):
        return self.nombre_curso        

class Estudiante(models.Model):
    curso = models.ForeignKey(Curso, on_delete=models.CASCADE)

    nombres = models.CharField('Nombres', max_length=20)
    apellidos = models.CharField('Apellidos', max_length=20)
    nombre_completo = models.CharField('Nombre Completo', max_length=40, blank=True)
    aciertoestudiante = models.DecimalField(max_digits=4, decimal_places=3, blank=True, null=True)

    preguntas = models.ManyToManyField(Preguntas,through='EstudiantePreguntas', blank=True)

    def save(self):
        self.nombre_completo = self.nombres + ' ' + self.apellidos
        return super(Estudiante, self).save()

    #class Meta:
    #    verbose_name = 'Estudiante'
    #    verbose_name_plural = 'Estudiantes del curso'
    #    ordering = ['-nombres', 'apellidos']

    def cursoestudiante(self):
        return self.curso

    def __str__(self):
        return self.nombres + ' ' + self.apellidos

class EstudiantePreguntas(models.Model):
    prueba = models.ForeignKey(Prueba, on_delete=models.CASCADE)
    estudiante = models.ForeignKey(Estudiante, on_delete=models.CASCADE)
    preguntas = models.ForeignKey(Preguntas, on_delete=models.CASCADE)

    correcto = models.BooleanField()

    def nombresestudiante(self):
        return  self.estudiante.nombres + ' ' + self.estudiante.apellidos

    def __str__(self):
        return self.estudiante.nombres + ' ' + self.estudiante.apellidos + ' ' + self.preguntas.pregunta + ' ' + str(self.correcto)

class EstudiantePruebas(models.Model):
    prueba = models.ForeignKey(Prueba, on_delete=models.CASCADE)
    estudiante = models.ForeignKey(Estudiante, on_delete=models.CASCADE)

    calificacion = models.DecimalField(max_digits=2, decimal_places=1, blank=True, null=True)

    def nombresestudiantee(self):
        return  self.estudiante.nombre_completo

    def __str__(self):
        return str(self.calificacion)

p2/base/forms.py
from django.forms import ModelForm
from .models import Curso, Estudiante, Prueba, Preguntas, EstudiantePreguntas, Tema

class CursoForm(ModelForm):
    class Meta:
        model = Curso
        fields = '__all__'

class EstudianteForm(ModelForm):
    class Meta:
        model = Estudiante
        fields = ('nombres','apellidos','nombre_completo',)   

class UEstudianteForm(ModelForm):
    class Meta:
        model = Estudiante
        fields = ('curso','nombres','apellidos','nombre_completo',)             

class EstudiantePreguntasForm(ModelForm):
    class Meta:
        model = EstudiantePreguntas
        fields = ('estudiante','correcto',)       

class PruebaForm(ModelForm):
    class Meta:
        model = Prueba
        fields = ('nombre_prueba', 'pruebareal',)

class PreguntasForm(ModelForm):

    class Meta:
        model = Preguntas
        fields = ('tema', 'pregunta',)

class UPreguntasForm(ModelForm):

    class Meta:
        model = Preguntas
        fields = ('pregunta',)

class TemaForm(ModelForm):
    class Meta:
        model = Tema
        fields = ('nombre_tema',)

p2/base/views.py
from django.shortcuts import render, redirect
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.forms import UserCreationForm
from django.db.models import Avg, Sum, Count
from .models import Curso, Estudiante, EstudiantePreguntas, EstudiantePruebas, Prueba, Preguntas, Tema
from .forms import CursoForm, EstudianteForm, UEstudianteForm, PruebaForm, PreguntasForm, UPreguntasForm, EstudiantePreguntasForm, TemaForm


def loginPage(request):
    calcular()
    page = 'login'
    if request.user.is_authenticated:
        return redirect('bienvenida')

    if request.method == 'POST':
        username = request.POST.get('username').lower()
        password = request.POST.get('password')

        try:
            user = User.objects.get(username=username)
        except:
            messages.error(request, 'El usuario ingresado no existe')

        user = authenticate(request, username=username, password=password)

        if user is not None:
            login(request, user)
            return redirect('bienvenida')
        else:
            messages.error(request, 'El usuario o contraseña no existe')

    context = {'page':page}
    return render(request, 'base/login_register.html', context)

def logoutUser(request):
    calcular()
    logout(request)
    return redirect('bienvenida')

def registerPage(request):
    calcular()
    form = UserCreationForm()
    if request.method == 'POST':
        form = UserCreationForm(request.POST)
        if form.is_valid():
            user = form.save(commit=False)
            user.username = user.username.lower()
            user.save()
            login(request, user)
            return redirect('bienvenida')
        else:
            messages.error(request, 'Un error ha ocurrido durante el registro')
    return render(request, 'base/login_register.html', {'form': form})

def bienvenida(request):
    calcular()
    data1 = Prueba.objects.all()
    data2 = EstudiantePruebas.objects.all()
    data3 = Preguntas.objects.all()
    data4 = Estudiante.objects.all()
    data5 = Tema.objects.all()
    context = {'data1': data1, 'data2': data2, 'data3': data3, 'data4': data4, 'data5': data5}
    return render(request, 'base/bienvenida.html', context)

@login_required(login_url='login')
def listacursos(request):
    calcular()
    cursos = Curso.objects.all()
    cursos_count = cursos.count()

    if request.method == 'POST':
        Curso.objects.create(nombre_curso = request.POST.get('nombre_curso'))
        return redirect('listacursos')

    context = {'cursos': cursos, 'cursos_count': cursos_count}
    return render(request, 'base/listacursos.html', context)

@login_required(login_url='login')
def actualizarCurso(request, pk):
    calcular()
    curso = Curso.objects.get(id=pk)
    form = CursoForm(instance=curso)
    if request.method == 'POST':
        form = CursoForm(request.POST, instance=curso)
        if form.is_valid():
            form.save()
            return redirect('listacursos')
    context = {'form': form}
    return render(request, 'base/curso_form.html', context)

@login_required(login_url='login')
def eliminarCurso(request, pk):
    calcular()
    curso = Curso.objects.get(id=pk)
    if request.method == 'POST':
        curso.delete()
        return redirect('listacursos')
    return render(request, 'base/delete.html', {'obj':curso})

@login_required(login_url='login')
def curso(request, pk):
    calcular()
    curso = Curso.objects.get(id=pk)
    context = {'curso': curso}
    return render(request, 'base/curso.html', context)

@login_required(login_url='login')
def crearEstudiante(request, pk):
    calcular()

    curso = Curso.objects.get(id=pk)
    context = {'curso': curso}

    form = EstudianteForm()
    if request.method == 'POST':
        form = EstudianteForm(request.POST)
        if form.is_valid():
            estudiante = form.save(commit=False)
            estudiante.curso_id = curso.id
            estudiante.save()
            return render(request, 'base/curso.html', context)
    context = {'form': form}
    return render(request, 'base/curso_form.html', context)

@login_required(login_url='login')
def actualizarEstudiante(request, pk):
    calcular()
    estudiante = Estudiante.objects.get(id=pk)

    curso = Curso.objects.get(id=estudiante.curso_id)
    context = {'curso': curso}

    form = UEstudianteForm(instance=estudiante)
    if request.method == 'POST':
        form = UEstudianteForm(request.POST, instance=estudiante)
        if form.is_valid():
            form.save()
            return render(request, 'base/curso.html', context)
    context = {'form': form}
    return render(request, 'base/curso_form.html', context)

@login_required(login_url='login')
def eliminarEstudiante(request, pk):
    calcular()
    estudiante = Estudiante.objects.get(id=pk)

    curso = Curso.objects.get(id=estudiante.curso_id)
    context = {'curso': curso}

    if request.method == 'POST':
        estudiante.delete()
        return render(request, 'base/curso.html', context)
    return render(request, 'base/delete.html', {'obj':estudiante})

@login_required(login_url='login')
def listapruebas(request):
    calcular()
    pruebas = Prueba.objects.filter(user=request.user)
    pruebas_count = pruebas.count()

    if request.method == 'POST':
        Prueba.objects.create(nombre_prueba = request.POST.get('nombre_prueba'), user=request.user)
        return redirect('listapruebas')

    context = {'pruebas': pruebas, 'pruebas_count': pruebas_count}
    return render(request, 'base/listapruebas.html', context)

@login_required(login_url='login')
def actualizarPrueba(request, pk):
    calcular()
    prueba = Prueba.objects.get(id=pk)
    form = PruebaForm(instance=prueba)
    if request.method == 'POST':
        form = PruebaForm(request.POST, instance=prueba)
        if form.is_valid():
            form.save()
            return redirect('listapruebas')
    context = {'form': form}
    return render(request, 'base/curso_form.html', context)

@login_required(login_url='login')
def eliminarPrueba(request, pk):
    calcular()
    prueba = Prueba.objects.get(id=pk)
    if request.method == 'POST':
        prueba.delete()
        return redirect('listapruebas')
    return render(request, 'base/delete.html', {'obj':prueba})  

@login_required(login_url='login')
def prueba(request, pk):
    calcular()
    prueba = Prueba.objects.get(id=pk)
    context = {'prueba': prueba}
    return render(request, 'base/prueba.html', context)

@login_required(login_url='login')
def crearPreguntas(request, pk):
    calcular()

    prueba = Prueba.objects.get(id=pk)
    context = {'prueba': prueba}

    form = PreguntasForm()
    if request.method == 'POST':
        form = PreguntasForm(request.POST)
        if form.is_valid():
            pregunta = form.save(commit=False)
            pregunta.prueba_id = prueba.id
            pregunta.save()
            return render(request, 'base/prueba.html', context)
    context = {'form': form}
    return render(request, 'base/curso_form.html', context) 

@login_required(login_url='login')
def actualizarPreguntas(request, pk):
    calcular()
    pregunta = Preguntas.objects.get(id=pk)

    prueba = Prueba.objects.get(id=pregunta.prueba_id)
    context = {'prueba': prueba}

    form = UPreguntasForm(instance=pregunta)
    if request.method == 'POST':
        form = UPreguntasForm(request.POST, instance=pregunta)
        if form.is_valid():
            form.save()
            return render(request, 'base/prueba.html', context)
    context = {'form': form}
    return render(request, 'base/curso_form.html', context)

@login_required(login_url='login')
def eliminarPreguntas(request, pk):
    calcular()
    pregunta = Preguntas.objects.get(id=pk)

    prueba = Prueba.objects.get(id=pregunta.prueba_id)
    context = {'prueba': prueba}

    if request.method == 'POST':
        pregunta.delete()
        return render(request, 'base/prueba.html', context)
    return render(request, 'base/delete.html', {'obj':pregunta})

@login_required(login_url='login')
def relacionarPreguntas(request, pk):
    calcular()

    a = Preguntas.objects.get(id=pk)
    context = {'a': a}

    if request.method == 'POST':
        form = EstudiantePreguntasForm(request.POST)
        if form.is_valid():
            relacion = form.save(commit=False)
            relacion.preguntas_id = a.id
            relacion.prueba_id = a.prueba_id
            relacion.save()
            return render(request, 'base/pregunta.html', context)
    else:
        form = EstudiantePreguntasForm()
    return render(request, 'base/curso_form.html', {'form': form})

@login_required(login_url='login')
def pregunta(response, pk):
    calcular()
    a = Preguntas.objects.get(id=pk)

    if response.method == 'POST':
        if response.POST.get('save'):
            for estudiantepreguntas in a.estudiantepreguntas_set.all():
                if response.POST.get('c' + str(estudiantepreguntas.id)) == 'clicked':
                    estudiantepreguntas.correcto = True
                else:
                    estudiantepreguntas.correcto = False
                estudiantepreguntas.save()
    return render(response, 'base/pregunta.html', {"a":a})

@login_required(login_url='login')
def eliminarRelacionPreguntas(request, pk):
    calcular()
    b = EstudiantePreguntas.objects.get(id=pk)

    a = Preguntas.objects.get(id=b.preguntas_id)
    context = {'a': a}

    if request.method == 'POST':
        b.delete()

p2/base/templates/base/bienvenida.html
{% extends 'base/main.html' %}

{% block content %}

<div>
    <div>
        <canvas id="myChart" width="400" height="400"></canvas>
        <script>
        const ctx = document.getElementById('myChart').getContext('2d');
        const myChart = new Chart(ctx, {
            type: 'bar',
            data: {
                labels: [{% for data1 in data1 %} '{{ data1.nombre_prueba }}', {% endfor %}],
                datasets: [{
                    label: 'Promedio de notas de la prueba',
                    data: [{% for data1 in data1 %} {{ data1.calificacionprueba }}, {% endfor%}],
                    backgroundColor: [
                        'rgba(255, 99, 132, 0.2)',
                        'rgba(54, 162, 235, 0.2)',
                        'rgba(255, 206, 86, 0.2)',
                        'rgba(75, 192, 192, 0.2)',
                        'rgba(153, 102, 255, 0.2)',
                        'rgba(255, 159, 64, 0.2)'
                    ],
                    borderColor: [
                        'rgba(255, 99, 132, 1)',
                        'rgba(54, 162, 235, 1)',
                        'rgba(255, 206, 86, 1)',
                        'rgba(75, 192, 192, 1)',
                        'rgba(153, 102, 255, 1)',
                        'rgba(255, 159, 64, 1)'
                    ],
                    borderWidth: 1
                }]
            },
            options: {
                maintainAspectRatio: false,
                responsive: true
            }
        });
        </script>
    </div>
    <br>

    <div>
        <canvas id="myChart2" width="400" height="400"></canvas>
        <script>
        const ctx2 = document.getElementById('myChart2').getContext('2d');
        const myChart2 = new Chart(ctx2, {
            type: 'bar',
            data: {
                labels: [{% for data2 in data2 %} {{ data2.estudiante_id }}, {% endfor %}],
                datasets: [{
                    label: 'Notas obtenidas por los estudiantes',
                    data: [{% for data2 in data2 %} {{ data2.calificacion }}, {% endfor%}],
                    backgroundColor: [
                        'rgba(255, 99, 132, 0.2)',
                        'rgba(54, 162, 235, 0.2)',
                        'rgba(255, 206, 86, 0.2)',
                        'rgba(75, 192, 192, 0.2)',
                        'rgba(153, 102, 255, 0.2)',
                        'rgba(255, 159, 64, 0.2)'
                    ],
                    borderColor: [
                        'rgba(255, 99, 132, 1)',
                        'rgba(54, 162, 235, 1)',
                        'rgba(255, 206, 86, 1)',
                        'rgba(75, 192, 192, 1)',
                        'rgba(153, 102, 255, 1)',
                        'rgba(255, 159, 64, 1)'
                    ],
                    borderWidth: 1
                }]
            },
            options: {
                maintainAspectRatio: false,
                responsive: true
            }
        });
        </script>
    </div>   
    <br>

    <div>
        <canvas id="myChart3" width="400" height="400"></canvas>
        <script>
        const ctx3 = document.getElementById('myChart3').getContext('2d');
        const myChart3 = new Chart(ctx3, {
            type: 'bar',
            data: {
                labels: [{% for data3 in data3 %} '{{ data3.pregunta }}', {% endfor %}],
                datasets: [{
                    label: 'Porcentaje de acierto en las pregunta',
                    data: [{% for data3 in data3 %} {{ data3.acierto }}, {% endfor%}],
                    backgroundColor: [
                        'rgba(255, 99, 132, 0.2)',
                        'rgba(54, 162, 235, 0.2)',
                        'rgba(255, 206, 86, 0.2)',
                        'rgba(75, 192, 192, 0.2)',
                        'rgba(153, 102, 255, 0.2)',
                        'rgba(255, 159, 64, 0.2)'
                    ],
                    borderColor: [
                        'rgba(255, 99, 132, 1)',
                        'rgba(54, 162, 235, 1)',
                        'rgba(255, 206, 86, 1)',
                        'rgba(75, 192, 192, 1)',
                        'rgba(153, 102, 255, 1)',
                        'rgba(255, 159, 64, 1)'
                    ],
                    borderWidth: 1
                }]
            },
            options: {
                maintainAspectRatio: false,
                responsive: true
            }
        });
        </script>
    </div>  
    <br>

    <div>
        <canvas id="myChart4" width="400" height="400"></canvas>
        <script>
        const ctx4 = document.getElementById('myChart4').getContext('2d');
        const myChart4 = new Chart(ctx4, {
            type: 'bar',
            data: {
                labels: [{% for data4 in data4 %} '{{ data4.nombre_completo }}', {% endfor %}],
                datasets: [{
                    label: 'Porcentaje de acierto de los estudiantes',
                    data: [{% for data4 in data4 %} {{ data4.aciertoestudiante }}, {% endfor%}],
                    backgroundColor: [
                        'rgba(255, 99, 132, 0.2)',
                        'rgba(54, 162, 235, 0.2)',
                        'rgba(255, 206, 86, 0.2)',
                        'rgba(75, 192, 192, 0.2)',
                        'rgba(153, 102, 255, 0.2)',
                        'rgba(255, 159, 64, 0.2)'
                    ],
                    borderColor: [
                        'rgba(255, 99, 132, 1)',
                        'rgba(54, 162, 235, 1)',
                        'rgba(255, 206, 86, 1)',
                        'rgba(75, 192, 192, 1)',
                        'rgba(153, 102, 255, 1)',
                        'rgba(255, 159, 64, 1)'
                    ],
                    borderWidth: 1
                }]
            },
            options: {
                maintainAspectRatio: false,
                responsive: true
            }
        });
        </script>
    </div>  
    <br>

    <div>
        <canvas id="myChart5" width="400" height="400"></canvas>
        <script>
        const ctx5 = document.getElementById('myChart5').getContext('2d');
        const myChart5 = new Chart(ctx5, {
            type: 'bar',
            data: {
                labels: [{% for data5 in data5 %} '{{ data5.nombre_tema }}', {% endfor %}],
                datasets: [{
                    label: 'Porcentaje de acierto de la unidad',
                    data: [{% for data5 in data5 %} {{ data5.aciertotema }}, {% endfor%}],
                    backgroundColor: [
                        'rgba(255, 99, 132, 0.2)',
                        'rgba(54, 162, 235, 0.2)',
                        'rgba(255, 206, 86, 0.2)',
                        'rgba(75, 192, 192, 0.2)',
                        'rgba(153, 102, 255, 0.2)',
                        'rgba(255, 159, 64, 0.2)'
                    ],
                    borderColor: [
                        'rgba(255, 99, 132, 1)',
                        'rgba(54, 162, 235, 1)',
                        'rgba(255, 206, 86, 1)',
                        'rgba(75, 192, 192, 1)',
                        'rgba(153, 102, 255, 1)',
                        'rgba(255, 159, 64, 1)'
                    ],
                    borderWidth: 1
                }]
            },
            options: {
                maintainAspectRatio: false,
                responsive: true
            }
        });
        </script>
    </div>  
    <br>
</div>
{% endblock content %}

p2/base/templates/base/curso.html
{% extends 'base/main.html' %}

{% block content %}

<h1>{{curso.nombre_curso}}</h1>
<div>
    <a href="{% url 'crear-estudiante' curso.id %}">Añadir estudiante</a>
    <div>
        {% for estudiante in curso.estudiante_set.all %}
            <div>
                <h3>{{estudiante.nombres}} {{estudiante.apellidos}}</h3>
                <a href="{% url 'actualizar-estudiante' estudiante.id %}">Actualizar estudiante</a>   
                <a href="{% url 'eliminar-estudiante' estudiante.id %}">Eliminar estudiante</a>     
            </div>
        {% empty %}
            No existe aún ningún estudiante relacionado al curso.
        {% endfor %}
    </div>
</div>
{% endblock content %}

p2/base/templates/base/curso_form.html
{% extends 'base/main.html' %}

{% block content %}

<div>
    <form method="POST" action="#">
        {% csrf_token %}
        {{form.as_p}}
        <input type="submit" value="Enviar">
    </form>
</div>

{% endblock content %}

p2/base/templates/base/delete.html
{% extends 'base/main.html' %}

{% block content %}

<form method="POST" action="">
    {% csrf_token %}
    <p>Estás seguro que quieres eliminar a "{{obj}}"?</p>
    <a href="{{request.META.HTTP_REFERER}}">Volver</a>
    <input type="submit" value="Confirmar">
</form>

{% endblock content %}

p2/base/templates/base/estudiantepreguntas1.html
{% extends 'base/main.html' %}

{% block content %}

<h1>{{preguntas.pregunta}}</h1>
<div>

    <div>
        {% for pregunta. in preguntas.estudiantepreguntas_set.all %}
            <div>
                <h3>{{estudiantepreguntas.estudiante_id}} {{estudiantepreguntas.correcto}}</h3>
            </div>
        {% empty %}
            No existe aún ninguna pregunta relacionado a la prueba.
        {% endfor %}
    </div>
</div>
{% endblock content %}

p2/base/templates/base/listacursos.html
{% extends 'base/main.html' %}

{% block content %}

<div class="wrapper">
    <h1>Cursos</h1>
    <h4>{{cursos_count}} cursos en el grado</h4>
    <br>
    <div>
        {% for curso in cursos %}
            <div>
                <h3><a href="/curso/{{curso.id}}">{{curso.nombre_curso}}</a></h3>
                <a href="{% url 'actualizar-curso' curso.id %}">Actualizar curso</a>   
                <a href="{% url 'eliminar-curso' curso.id %}">Eliminar curso</a>           
            </div>
        {% empty %}
            No existe aún ningún curso añadido.
        {% endfor %}
    </div>
</div>
<br>
{% if request.user.is_authenticated %}
<div>
    <form method="POST" action="">
        {% csrf_token %}
        <input type="text" name="nombre_curso" placeholder="Agrega un curso aquí"/>
        <input type="submit" value="Añadir"/>
    </form>
</div>
{% endif %}
{% endblock content %}

p2/base/templates/base/listapruebas.html
{% extends 'base/main.html' %}

{% block content %}

<div class="wrapper"></div>
    <h1>Pruebas</h1>
    <h4>{{pruebas_count}} pruebas añadidas</h4>
    <br>
    <div>
        {% for prueba in pruebas.all %}
            <div>
                <h3><a href="/prueba/{{prueba.id}}">{{prueba.nombre_prueba}}</a></h3>
                <a href="{% url 'actualizar-prueba' prueba.id %}">Actualizar prueba</a> 
                <a href="{% url 'eliminar-prueba' prueba.id %}">Eliminar prueba</a>     
            </div>
        {% empty %}
            No existe aún ninguna prueba añadida.
        {% endfor %}
    </div>
</div>
<br>
{% if request.user.is_authenticated %}
<div>
    <form method="POST" action="">
        {% csrf_token %}
        <input type="text" name="nombre_prueba" placeholder="Agrega una prueba aquí"/>
        <input type="submit" value="Añadir"/>
    </form>
</div>
{% endif %}
{% endblock content %}

p2/base/templates/base/prueba.html
{% extends 'base/main.html' %}

{% block content %}

<h1>{{prueba.nombre_prueba}}</h1>
<div>
    <a href="{% url 'crear-preguntas' prueba.id %}">Añadir pregunta</a>
    <div>
        {% for preguntas in prueba.preguntas_set.all %}
            <div>
                <h3><a href="/pregunta/{{preguntas.id}}">{{preguntas.pregunta}}</a></h3>

                <a href="{% url 'actualizar-preguntas' preguntas.id %}">Actualizar pregunta</a> 
                <a href="{% url 'eliminar-preguntas' preguntas.id %}">Eliminar pregunta</a>
            </div>
        {% empty %}
            No existe aún ninguna pregunta relacionado a la prueba.
        {% endfor %}
    </div>
</div>
{% endblock content %}